// <auto-generated />
using FoodMenuApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodMenuApi.Migrations
{
    [DbContext(typeof(MenuAppDbContext))]
    partial class MenuAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FoodMenuApi.Models.FoodCategory", b =>
                {
                    b.Property<string>("name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("name");

                    b.ToTable("FoodCategories");
                });

            modelBuilder.Entity("FoodMenuApi.Models.FoodItem", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("FoodCategoryname")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsInGallery")
                        .HasColumnType("bit");

                    b.Property<float>("calories")
                        .HasColumnType("real");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("imageUrl")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("isVegan")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("price")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("FoodCategoryname");

                    b.ToTable("FoodItems");
                });

            modelBuilder.Entity("FoodMenuApi.Models.FoodItem", b =>
                {
                    b.HasOne("FoodMenuApi.Models.FoodCategory", null)
                        .WithMany("items")
                        .HasForeignKey("FoodCategoryname");
                });

            modelBuilder.Entity("FoodMenuApi.Models.FoodCategory", b =>
                {
                    b.Navigation("items");
                });
#pragma warning restore 612, 618
        }
    }
}
